language: python
python: 3.5
sudo: false
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=static_check
install: pip install tox
script: tox -e $TOX_ENV
deploy:
  provider: pypi
  user: mavlyutov
  distributions: "sdist bdist_wheel"
  password:
    secure: Aimu/wB30KsebRDHFLJdo5M6AsrKfhl6dL5wrdbFMeyklx6us18Rg6KD+KagjrHwVzxMifi2O/ael7YKSXN6nGXFo0VQCG3CNPYCnRvgLqh1IFTMvmVpWn3R4J7oi+UKc40Ipeaq+3yuZo+ssESXpjQIwIBMxifSA78Q3hqmgWA=
  on:
    tags: true
    branch: master
